     civic-annotator    62   2018-10-15 15:09:56,476   Initialized civic-annotator
     civic-annotator   169   2018-10-15 15:09:56,476   Running civic-annotator
     civic-annotator    71   2018-10-15 15:09:56,478   invalid literal for int() with base 10: '-'
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/cravat/base_annotator.py", line 171, in run
    for lnum, input_data, secondary_data in self._get_input():
  File "/anaconda3/lib/python3.6/site-packages/cravat/base_annotator.py", line 439, in _get_input
    for lnum, reader_data in self.primary_input_reader.loop_data('dict'):
  File "/anaconda3/lib/python3.6/site-packages/cravat/inout.py", line 339, in loop_data
    data = self.line_to_data_dict(l)
  File "/anaconda3/lib/python3.6/site-packages/cravat/inout.py", line 359, in line_to_data_dict
    return self.toks_to_data_dict(toks)
  File "/anaconda3/lib/python3.6/site-packages/cravat/inout.py", line 377, in toks_to_data_dict
    out[col_name] = int(tok)
ValueError: invalid literal for int() with base 10: '-'
